#Machine learning figures
#data generated by /Users/Art/Drive/PhD/Experiments/Aging Signature/000_FINAL/12_machine_learning/py_copies/fit_predict.py
library(tidyverse)
library(ggrepel)
source("/Users/Art/Drive/PhD/Experiments/Aging Signature/plotting_theme.R")
setwd("/Users/Art/Drive/PhD/Experiments/Aging Signature/000_FINAL/12_machine_learning/selected_AS/202101_outputs/clean/")

#MDS all genes
all.genes <- read.csv("Allgenes_MDS_clean.csv", stringsAsFactors = F, header = T) %>%
  as_tibble() %>%
  mutate(ages.actual = recode(ages.actual, "0" = "young", "1" = "aged")) %>%
  mutate(ages.predicted = recode(ages.predicted, "0" = "young", "1" = "aged")) %>%
  mutate(mismatches = recode(mismatches, "0" = "match", "1" = "match", "2" = "mismatch")) %>%
  mutate(ages.actual = factor(ages.actual, levels = c("young", "aged"))) %>%
  mutate(ages.predicted = factor(ages.predicted, levels = c("young", "aged")))

all.plot <- 
  ggplot(all.genes, aes(x = PC1, y = PC2, shape = factor(ages.actual), color = factor(ages.actual))) +
  geom_point(size = 3) +
  scale_x_continuous(n.breaks = 5) +
  scale_y_continuous(n.breaks = 5) +
  scale_color_manual(values = c("grey", "red"), labels = c("young", "aged")) +
  labs(title = "MDS - all genes", color = "measured cell age", shape = "measured cell age") +
  facet_wrap(study ~., scales = "free") +
  theme_pb() +
  theme(aspect.ratio = 1)

all.plot

#Best20-ADAboost
ada.20 <- read.csv("Best20_MDS_ADAboost_clean.csv", header = T, stringsAsFactors = F) %>%
  as_tibble()
  # mutate(ages.actual = recode(ages.actual, "0" = "young", "1" = "aged")) %>%
  # mutate(ages.predicted = recode(ages.predicted, "0" = "young", "1" = "aged")) %>%
  # mutate(mismatches = recode(mismatches, "0" = "match", "1" = "match", "2" = "mismatch")) %>%
  # mutate(ages.actual = factor(ages.actual, levels = c("young", "aged"))) %>%
  # mutate(ages.predicted = factor(ages.predicted, levels = c("young", "aged")))

ada20.plot <- 
  ggplot(ada.20, aes(x = PC1, y = PC2, shape = factor(ages.actual), color = factor(mismatches))) +
  geom_point(size = 3) +
  scale_x_continuous(n.breaks = 5) +
  scale_y_continuous(n.breaks = 5) +
  scale_color_manual(values = c("grey", "red", "#fec44f"), labels = c("young", "aged", "mismatch")) +
  labs(title = "best20 - ada", shape = "measured cell age", color = "predicted cell age") +
  scale_shape_discrete(labels = c("young", "aged")) +
  facet_wrap(study ~., scales = "free") +
  theme_pb() +
  theme(aspect.ratio = 1)

ada20.plot


#Best20-RNDforrest
rdn.20 <- read.csv("Best20_MDS_RDNforrest_clean.csv", header = T, stringsAsFactors = F) %>%
  as_tibble()

rdn20.plot <-
  ggplot(rdn.20, aes(x = PC1, y = PC2, shape = factor(ages.actual), color = factor(mismatches))) +
  geom_point(size = 3) +
  scale_x_continuous(n.breaks = 5) +
  scale_y_continuous(n.breaks = 5) +
  scale_color_manual(values = c("grey", "red", "#fec44f"), labels = c("young", "aged", "mismatch")) +
  labs(title = "best20 - rdn", shape = "measured cell age", color = "predicted cell age") +
  scale_shape_discrete(labels = c("young", "aged")) +
  facet_wrap(study ~., scales = "free") +
  theme_pb() +
  theme(aspect.ratio = 1)

rdn20.plot

#Best5-ADAboost
ada.5 <- read.csv("Best5_MDS_ADAboost_clean.csv", header = T, stringsAsFactors = F) %>%
  as_tibble() 
  
  ada5.plot <- 
  ggplot(ada.5, aes(x = PC1, y = PC2, shape = factor(ages.actual), color = factor(mismatches))) +
  geom_point(size = 3) +
  #scale_x_continuous(n.breaks = 5) +
  scale_y_continuous(n.breaks = 5) +
  scale_color_manual(values = c("grey", "red", "#fec44f"), labels = c("young", "aged", "mismatch")) +
  labs(title = "best5 - ada", shape = "measured cell age", color = "predicted cell age") +
  scale_shape_discrete(labels = c("young", "aged")) +
  facet_wrap(study ~., scales = "free") +
  theme_pb() +
  theme(aspect.ratio = 1)

ada5.plot

#Best5-RNDforrest
rdn.5 <- read.csv("Best5_MDS_RDNforrest_clean.csv", header = T, stringsAsFactors = F) %>%
  as_tibble()

rdn5.plot <-
  ggplot(rdn.5, aes(x = PC1, y = PC2, shape = factor(ages.actual), color = factor(mismatches))) +
  geom_point(size = 3) +
  scale_x_continuous(n.breaks = 5) +
  scale_y_continuous(n.breaks = 5) +
  scale_color_manual(values = c("grey", "red", "#fec44f"), labels = c("young", "aged", "mismatch")) +
  labs(title = "best5 - rdn", shape = "measured cell age", color = "predicted cell age") +
  scale_shape_discrete(labels = c("young", "aged")) +
  facet_wrap(study ~., scales = "free") +
  theme_pb() +
  theme(aspect.ratio = 1)

rdn5.plot


#Scores
scores <- read.csv("scores_clean.csv", header = T, stringsAsFactors = F) %>%
  gather(key = "test.set", value = "score", -c(train.set, best, classification)) %>%
  select(train.set, test.set, score, best, classification)


ada20.score <- ggplot(data = filter(scores, best == "20" & classification == "ADAboost"), 
                      aes(x = train.set, 
                          y = test.set,
                          fill = score ))+
  scale_fill_viridis(alpha = 1) +
  geom_tile(color = "white") +
  geom_text(aes(x = train.set, y = test.set, label = score), color = "white", size = 3) +
  labs(y = " ", x = " ", title = "ada - 20") +
  theme_pb()+
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.background = element_blank(),
    axis.text.x = element_text(angle = 90, hjust = 1, size = 15, color = 'black'),
    legend.text = element_text(size = 15, color = 'black'),
    legend.title = element_text(size = 15, color = 'black'),
    aspect.ratio = 1)
ada20.score

rnd20.score <- ggplot(data = filter(scores, best == "20" & classification == "RNDforrest"), 
                      aes(x = train.set, 
                          y = test.set,
                          fill = score ))+
  scale_fill_viridis(alpha = 1) +
  geom_tile(color = "white") +
  geom_text(aes(x = train.set, y = test.set, label = score), color = "white", size = 3) +
  labs(y = " ", x = " ", title = "rnd - 20") +
  theme_pb()+
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.background = element_blank(),
    axis.text.x = element_text(angle = 90, hjust = 1, size = 15, color = 'black'),
    legend.text = element_text(size = 15, color = 'black'),
    legend.title = element_text(size = 15, color = 'black'),
    aspect.ratio = 1)
rnd20.score

ada5.score <- ggplot(data = filter(scores, best == "5" & classification == "ADAboost"), 
                      aes(x = train.set, 
                          y = test.set,
                          fill = score ))+
  scale_fill_viridis(alpha = 1) +
  geom_tile(color = "white") +
  geom_text(aes(x = train.set, y = test.set, label = score), color = "white", size = 3) +
  labs(y = " ", x = " ", title = "ada - 5") +
  theme_pb()+
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.background = element_blank(),
    axis.text.x = element_text(angle = 90, hjust = 1, size = 15, color = 'black'),
    legend.text = element_text(size = 15, color = 'black'),
    legend.title = element_text(size = 15, color = 'black'),
    aspect.ratio = 1)
ada5.score

rnd5.score <- ggplot(data = filter(scores, best == "5" & classification == "RNDforrest"), 
                      aes(x = train.set, 
                          y = test.set,
                          fill = score ))+
  scale_fill_viridis(alpha = 1) +
  geom_tile(color = "white") +
  geom_text(aes(x = train.set, y = test.set, label = score), color = "white", size = 3) +
  labs(y = " ", x = " ", title = "rnd - 5") +
  theme_pb()+
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.background = element_blank(),
    axis.text.x = element_text(angle = 90, hjust = 1, size = 15, color = 'black'),
    legend.text = element_text(size = 15, color = 'black'),
    legend.title = element_text(size = 15, color = 'black'),
    aspect.ratio = 1)
rnd5.score
