#Machine learning figures
#data generated by /Users/Art/Drive/PhD/Experiments/Aging Signature/000_FINAL/12_machine_learning/py_copies/fit_predict.py
library(tidyverse)
library(ggrepel)
source("/Users/Art/Drive/PhD/Experiments/Aging Signature/plotting_theme.R")
setwd("/Users/Art/Drive/PhD/Experiments/Aging Signature/000_FINAL/12_machine_learning/selected_AS/202101_outputs/")

#Bar plot gene locations
df <- read.csv("Best20_AS_locations_percentages.csv", header = T, stringsAsFactors = F) %>%
  mutate(location = factor(location, levels = rev(c("membrane",
                                                "cytoplasm",
                                                "nucleus",
                                                "extracel",
                                                "ER",
                                                "other"))))

ggplot(df, aes(x = set, y = count.per, fill = location)) + 
  geom_bar(stat = "identity") +
  coord_flip() +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme_pb() +
  theme(aspect.ratio = 0.5)
